# Import the Libraries

In [6]:
import numpy as np
import pandas as pd

# Read the training dataset

In [8]:
df = pd.read_csv(r'C:\Users\Anshul Singh\Downloads\hackerearth\Machine Leaning contest\Employee\Dataset\Train.csv')

In [9]:
df = df.reindex(columns=['Employee_ID','Gender','Relationship_Status','Hometown','Unit','Decision_skill_possess','Compensation_and_Benefits','Age','Education_Level','Time_of_service','Time_since_promotion','growth_rate','Travel_Rate','Post_Level','Pay_Scale','Work_Life_balance','VAR1','VAR2','VAR3','VAR4','VAR5','VAR6','VAR7','Attrition_rate'])

# Here I catrgorize the data (for string values)

In [10]:
for col in df.select_dtypes(include='object').columns: 
    df[col]=pd.Categorical(df[col],categories=np.unique(df[col])).codes

# Defining dependent and independent varaibles

In [11]:
X = df.iloc[:, 1:-1].values
y = df.iloc[:, -1].values

# Handle missing data values in train set

In [12]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:])
X[:,1:] = imputer.transform(X[:,1:])
print(X)

[[0. 0. 1. ... 4. 5. 3.]
 [1. 1. 3. ... 3. 5. 3.]
 [0. 0. 0. ... 3. 8. 3.]
 ...
 [0. 1. 3. ... 4. 8. 3.]
 [0. 0. 4. ... 3. 6. 3.]
 [0. 0. 1. ... 4. 5. 3.]]


# Here I used Multiple Linear Regression to train the model

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X[:,6:9] = sc.fit_transform(X[:,6:9])
print(X[:,6:10])
#y = sc.transform(y)

[[ 0.18009898  0.76255659 -0.91505508  4.        ]
 [-1.18359795 -0.17638732 -0.81755388  4.        ]
 [ 1.39227403 -0.17638732  1.32747267  3.        ]
 ...
 [ 0.71042557 -0.17638732 -0.33004784  1.        ]
 [ 0.55890369 -0.17638732  1.03496905  1.        ]
 [ 1.39227403 -0.17638732  0.83996664  2.        ]]


In [14]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X, y)

C:\Users\Anshul Singh\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

# Read the test dataset

In [17]:
testset = pd.read_csv(r'C:\Users\Anshul Singh\Downloads\hackerearth\Machine Leaning contest\Employee\Dataset\Test.csv')
testset = testset.reindex(columns=['Employee_ID','Gender','Relationship_Status','Hometown','Unit','Decision_skill_possess','Compensation_and_Benefits','Age','Education_Level','Time_of_service','Time_since_promotion','growth_rate','Travel_Rate','Post_Level','Pay_Scale','Work_Life_balance','VAR1','VAR2','VAR3','VAR4','VAR5','VAR6','VAR7'])

In [18]:
for col in testset.select_dtypes(include='object').columns: 
    testset[col]=pd.Categorical(testset[col],categories=np.unique(testset[col])).codes

# Taking all independent vairable

In [19]:

test = testset.iloc[:,1:].values
test[:,6:9] = sc.transform(test[:,6:9])

# Handle missing data values in test set

In [20]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(test)
test = imputer.transform(test)
test

array([[0., 1., 3., ..., 1., 8., 4.],
       [1., 1., 2., ..., 2., 8., 2.],
       [1., 0., 3., ..., 1., 9., 3.],
       ...,
       [0., 1., 2., ..., 4., 8., 4.],
       [0., 0., 3., ..., 3., 9., 2.],
       [0., 1., 1., ..., 2., 8., 5.]])

# Predict the result

In [21]:
y_pred = lin_reg.predict(test)

# Taking Emp Id into a variable

In [23]:
testset = pd.read_csv(r'C:\Users\Anshul Singh\Downloads\hackerearth\Machine Leaning contest\Employee\Dataset\Test.csv')
ids = testset.iloc[:,:1].values

# Making a new dataframe with adding Emp id column

In [24]:
new = pd.DataFrame(ids)

# Adding a new coloumn of Attrition rate 

In [25]:
new['Attrition_rate'] = y_pred 

# Naming the both Column

In [26]:
new.columns = ['Employee_ID','Attrition_rate']


# Storing the dataframe into a CSV File

In [27]:
new.to_csv('Final124.csv',index=False) 